### ISSUE TITLE
Is this directive requires the latest md-data-table in order to work?

### ISSUE THREAD

**Issue by egantz** [daniel-nagy/fixed-table-header#10]
I have just installed it and for some reason it doesn't work.
Claiming the directive 'fixed.table.header' cannot be found.

any ideas?
I'm working with md-data-table v0.8 something. is that related to my case?

Thanks a ton.

**Comment by daniel-nagy** [comment]
No the data table version shouldn't make a difference. Can you confirm that the file is being fetched by the browser?

<img width="1440" alt="screen shot 2016-03-16 at 11 05 17 am" src="https://cloud.githubusercontent.com/assets/1622446/13817092/487a23da-eb67-11e5-9d1c-a98c468cb1f6.png">

Also, you will probably want to make sure it is loaded before the entry point of you application.

**Comment by egantz** [comment]
Sorry for the delay. eventually I had a weird issue with Gulp. all good, now I can see the file being loaded in the Network tab. tried to insert the fix-head directive and I get this error: `[$compile:ctreq] Controller 'mdTable', required by directive 'mdColumn', can't be found!`

What am I doing wrong?

Using md-data-table v0.9.14

**Comment by daniel-nagy** [comment]
@eGantz closing this issue, head over to [#152](https://github.com/daniel-nagy/md-data-table/issues/152#issuecomment-198817064)

**Comment by daniel-nagy** [comment]
Sorry, I just realized this issue may be specific to the `fix-head` Directive since you started getting the error after using it. You can open another issue if you like.

**Comment by egantz** [comment]
Thanks! Yeah it happens whenever I add the directive `fix-head` to the `md-head`.
are you aware of this issue? is that related to the version I have?
