### ISSUE TITLE
Clones head way outside enclosing DIV

### ISSUE THREAD

**Issue by smlombardi** [daniel-nagy/fixed-table-header#18]
My table is in a bootstrap grid:

``` html
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>PMT test</h1>
       <table class="table">
         <thead fix-head>
           <tr>
             ...
           </tr>
         </thead>
         <tbody>
           <tr ng-repeat="d in pmtData">
             ...
           </tr>
         </tbody>
       </table>
    </div>
  </div>
</div>
```

And with this directive I get:
![screen shot 2016-07-13 at 10 20 37 am](https://cloud.githubusercontent.com/assets/835148/16806681/7c9ff142-48e3-11e6-92c3-a46f0b72f996.png)

As you can see, the thead is rendered above the h1 that precedes the table. And its not even fixed.

**Comment by SandyCarney** [comment]
Move h1 header to the top and try..
`<div class="container-fluid">
  <div class="row">
    <h1>PMT test</h1>
    <div class="col-md-12">
        <table class="table">
         <thead fix-head>
           <tr>
             ...
           </tr>
         </thead>
         <tbody>
           <tr ng-repeat="d in pmtData">
             ...
           </tr>
         </tbody>
       </table>
    </div>
  </div>
</div>`

**Comment by smlombardi** [comment]
That's not valid bootstrap code. I bagged it and found another directive that works.
