### ISSUE TITLE
Is this module not available on bower?

### ISSUE THREAD

**Issue by Dhara-ZYMR** [daniel-nagy/fixed-table-header#5]
Is this module not available on bower?

bower install angular-fixed-table-header says package not found.

**Comment by daniel-nagy** [comment]
No I haven't published it anywhere.

**Comment by Dhara-ZYMR** [comment]
Can you please publish it? It will be easier for us to use.
And Thanks for this very useful module..!!

**Comment by cbierman** [comment]
@Dhara-ZYMR You can still install it through bower using a Git endpoint.

e.g. `bower install https://github.com/daniel-nagy/fixed-table-header.git --save`

**Comment by daniel-nagy** [comment]
This module should be available on Bower now.
