### ISSUE TITLE
Support with md-data-table

### ISSUE THREAD

**Issue by pdore-netfore** [daniel-nagy/fixed-table-header#6]
I have an md-data-table:
```
<md-table-container>
        <table md-table>
            <thead md-head md-order="order" md-on-reorder="onReorder">
                <tr md-row>
                    <th md-column ng-repeat="column in columns" md-order-by="{{column.name}}"><span translate="{{column.name}}"></span></th>
                </tr>
            </thead>
            <tbody md-body>
                    <tr md-row ng-repeat="item in items | orderBy: order">
                        <td md-cell ng-repeat-start="column in columns">
                            ...
                        </td>
                    </tr>
            </tbody>
        </table>
</md-table-container>
````

To add a fixed header, I've added ```fix-head``` to the ```<thead>``` element and giving the ```<md-table-container>``` a fixed height and overflow.

White-space shows above the table on initial load and the header doesn't stick when scrolling.

Please help!

**Comment by pdore-netfore** [comment]
Seems to be an issues with the use of ng-repeat to populate the th's

**Comment by daniel-nagy** [comment]
I don't think this plays nice with `ng-repeat`. #2

If you make a Codepen I'll take a look at it. You can fork the [Codepen](http://codepen.io/anon/pen/qbLaMb?editors=101) from the demo, it already uses the data table. Otherwise you may not be able to use `ng-repeat` within the header.

**Comment by pdore-netfore** [comment]
**Without fix-head**
http://codepen.io/pdore/pen/XdmeVr?editors=101

**With fix-head**
http://codepen.io/pdore/pen/qZOPxN?editors=101

**Comment by daniel-nagy** [comment]
`ng-repeat` should work now, I've also published this to bower and npm.
