### ISSUE TITLE
bower.json configuration problem

### ISSUE THREAD

**Issue by Toninh0** [daniel-nagy/fixed-table-header#9]
It seems that there is a problem in bower.json main section.

There is no "dist" directory:

"main": [
    "dist/fixed-table-header.js"
]

**Comment by daniel-nagy** [comment]
I just pulled it down from Bower and there is in fact a `dist/` directory.

**Comment by Toninh0** [comment]
Sounds weird I don't get any :/

**Comment by daniel-nagy** [comment]
<img width="663" alt="screen shot 2016-03-15 at 11 44 56 am" src="https://cloud.githubusercontent.com/assets/1622446/13783873/7937891e-eaa3-11e5-8cb6-58cfe9396e23.png">

**Comment by Toninh0** [comment]
Oh We are discussing about **fixed-table-header**

**Comment by daniel-nagy** [comment]
Oh sorry, you're right. I will fix it now.

**Comment by Toninh0** [comment]
Thank you Daniel. 
Great work by the way

**Comment by daniel-nagy** [comment]
Okay should be fixed now. Thank you.

**Comment by Toninh0** [comment]
It is.
Thanks
